// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDORvzCyvzIDg0ISZB3RrYTeCy7gikSqSk',
    appId: '1:357192806400:web:d87921af22eb4594e8e8e5',
    messagingSenderId: '357192806400',
    projectId: 'demoavril-a246c',
    authDomain: 'demoavril-a246c.firebaseapp.com',
    storageBucket: 'demoavril-a246c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4X9cI4Gn6YdDkoLVDWvPVkvCclYFUQqw',
    appId: '1:357192806400:android:0a9f8728543f91d7e8e8e5',
    messagingSenderId: '357192806400',
    projectId: 'demoavril-a246c',
    storageBucket: 'demoavril-a246c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcMydT5Lgu6I84twbvdfsNw0vVm7Lz5xw',
    appId: '1:357192806400:ios:3636eea718c55909e8e8e5',
    messagingSenderId: '357192806400',
    projectId: 'demoavril-a246c',
    storageBucket: 'demoavril-a246c.appspot.com',
    iosBundleId: 'com.example.avril',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcMydT5Lgu6I84twbvdfsNw0vVm7Lz5xw',
    appId: '1:357192806400:ios:3636eea718c55909e8e8e5',
    messagingSenderId: '357192806400',
    projectId: 'demoavril-a246c',
    storageBucket: 'demoavril-a246c.appspot.com',
    iosBundleId: 'com.example.avril',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDORvzCyvzIDg0ISZB3RrYTeCy7gikSqSk',
    appId: '1:357192806400:web:0fb2a2020e94aa25e8e8e5',
    messagingSenderId: '357192806400',
    projectId: 'demoavril-a246c',
    authDomain: 'demoavril-a246c.firebaseapp.com',
    storageBucket: 'demoavril-a246c.appspot.com',
  );
}
